### ISSUE TITLE
where to find the "STraTUS.pdf" file?

### ISSUE THREAD

**Issue by liamxg** [mdhall272/TTsampler#1]
@mdhall272

**Comment by xin-huang** [comment]
I believe you can find it here: https://cran.r-project.org/web/packages/STraTUS/STraTUS.pdf

**Comment by mdhall272** [comment]
Yes, indeed, this is a CRAN package and the documentation can be found there. Sorry for the delay in replying.

**Comment by liamxg** [comment]
Dear @mdhall272, and @xin-huang,

Thanks.

Best,
Liam
